# Generated by Django 5.1.6 on 2025-04-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_vacancy_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', max_length=20),
        ),
    ]
