# Generated by Django 5.1.6 on 2025-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_vacancy_requirements_vacancy_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
