# Generated by Django 5.1.5 on 2025-05-20 01:14

import CVapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applied_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_rate', models.FloatField()),
                ('state', models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('vacancy_text', models.CharField(max_length=1000)),
                ('extracted_text', models.TextField()),
                ('upgraded_cv', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.BinaryField(default=CVapp.models.get_default_array)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Saved_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
