# Generated by Django 5.1.6 on 2025-03-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='cv',
            new_name='file',
        ),
    ]
