# Generated by Django 5.1.6 on 2025-04-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVapp', '0002_rename_cv_cv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('vacancy_text', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('extracted_text', models.TextField()),
                ('upgraded_text', models.TextField()),
                ('match_rate', models.FloatField()),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CV',
        ),
    ]
