# Generated by Django 5.1.6 on 2025-03-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVapp', '0002_rename_cv_cv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='cv_upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_extract', models.TextField()),
                ('date', models.DateField()),
                ('cv_upgraded', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='CV',
        ),
    ]
