# Generated by Django 5.1.6 on 2025-04-23 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVapp', '0003_resume_delete_cv'),
        ('offer', '0002_vacancy_delete_offer'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='match_rate',
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.CreateModel(
            name='Applied_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_rate', models.FloatField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVapp.resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.vacancy')),
            ],
        ),
    ]
