# Generated by Django 5.1.6 on 2025-04-23 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVapp', '0004_remove_resume_match_rate_alter_resume_uploaded_by_and_more'),
        ('offer', '0004_vacancy_requirements_vacancy_state'),
        ('users', '0002_user_is_authenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='upgraded_text',
            new_name='upgraded_cv',
        ),
        migrations.AddField(
            model_name='applied_resume',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applied_resume',
            name='state',
            field=models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
        migrations.CreateModel(
            name='Saved_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.vacancy')),
            ],
        ),
    ]
