# Generated by Django 5.1.6 on 2025-04-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVapp', '0005_rename_upgraded_text_resume_upgraded_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/resume/name'),
        ),
    ]
