# Generated by Django 5.1.6 on 2025-04-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVapp', '0006_alter_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/resumes/<django.db.models.fields.CharField>'),
        ),
    ]
