# Generated by Django 5.1.6 on 2025-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVapp', '0008_alter_resume_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
